const LOGGED_IN = 'LOGGED_IN';
const INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
const UNAUTHENTICATED = 'UNAUTHENTICATED';

export default {
    LOGGED_IN,
    INVALID_CREDENTIALS,
    UNAUTHENTICATED
};
